version: '3.8'
services:
  api:
    image: fap-backend
    container_name: fap-backend
    ports:
      - "8080:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://0.0.0.0:80
      ConnectionStrings__DefaultConnection: "Server=host.docker.internal,1433;Database=FapDb;User Id=sa;Password=12345;TrustServerCertificate=True;Encrypt=False;"
    extra_hosts:
      - "host.docker.internal:host-gateway"
